### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by Heltrato** [ldtteam/GraphicsExpanded#6]
`---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 6/20/19 12:23 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Animatrix (animatrix)
Caused by: java.lang.IllegalStateException: Could not load shader.
	at com.ldtteam.graphicsexpanded.shader.program.ShaderProgram.loadShader(ShaderProgram.java:96)
	at com.ldtteam.graphicsexpanded.shader.program.ShaderProgram.<init>(ShaderProgram.java:31)
	at com.ldtteam.animatrix.render.shader.AnimatrixShader.<init>(AnimatrixShader.java:23)
	at com.ldtteam.animatrix.ModAnimatrix.onFMLPreInitialization(ModAnimatrix.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
`
My forge version 1.12.2-14.23.5.2838

**Comment by marchermans** [comment]
Hello, I would like to know what you are exactly doing?
Are shaders supported on your platform?

What is your hardware?

**Comment by Heltrato** [comment]
Hello what i did is i just put the 2 mods (required dependency and animatrix) and test it out.
im using a nvdia geforce 920m

**Comment by marchermans** [comment]
Okey. Interesting i will test it later then.

**Comment by Heltrato** [comment]
Thanks for the fast help !

**Comment by marchermans** [comment]
No problem, will see what is causing this.

**Comment by Heltrato** [comment]
Alright looking foward to it 💯

**Comment by Heltrato** [comment]
Here's also a crash log from my friend that also i asked yesterday to test the mod out. 
https://pastebin.com/NZWSViAc
